matrix:
  include:
    # 一、构建前端项目
    - language: node_js
      ### 1.1 指定node版本
      node_js:
        - 10.16.1
      ### 1.2 指定github分支
      branches:
        only:
          - master
      ### 1.3 进入前端项目目录
      before_install:
        - openssl aes-256-cbc -K $encrypted_a7dfe7f624ec_key -iv $encrypted_a7dfe7f624ec_iv  -in
          id_rsa.enc -out ~/.ssh/id_rsa -d
        - chmod 600 ~/.ssh/id_rsa
        - echo -e "Host $SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - cd science-innovate-vue
      ### 1.4 指定安装脚本
      install:
        - npm install
      ### 1.5 指定了需要运行的测试脚本
      script:
        - npm run build
        - docker build . -t "soldierdocker/science-innovate-vue:latest"
      addons:
        ssh_known_hosts:
          - "$SERVER_IP"
      ### 1.6 提交镜像并登录服务器部署项目
      after_success:
        - docker login -u=$DOCKER_NAME -p="$DOCKER_PWD"
        - docker push soldierdocker/science-innovate-vue:latest
        - chmod 600 ~/.ssh/id_rsa
        - rsync -az --delete ./docker-compose.yml root@$SERVER_IP:science-innovate-vue/
        - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$SERVER_IP "cd science-innovate-vue/;docker-compose
          -f docker-compose.yml pull;docker-compose -f docker-compose.yml up -d;exit"
    # 二、构建前端项目
    - language: java
      ### 2.1 指定需要的服务
      services:
        - docker
      ### 2.2 指定是否需要root权限
      sudo: required
      ### 2.3 指定github分支
      branches:
        only:
          - master
      ### 2.4 进入后端项目目录
      before_install:
        - openssl aes-256-cbc -K $encrypted_a7dfe7f624ec_key -iv $encrypted_a7dfe7f624ec_iv
          -in id_rsa.enc -out ~/.ssh/id_rsa -d
        - chmod 600 ~/.ssh/id_rsa
        - echo -e "Host $SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - cd science-innovate-admin
      ### 2.5 指定了需要运行的测试脚本
      script:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - docker build . -t "soldierdocker/science-innovate-admin:latest"
      ### 2.6 提交镜像并登录服务器部署项目
      after_success:
        - docker login -u=$DOCKER_NAME -p="$DOCKER_PWD"
        - docker push soldierdocker/science-innovate-admin:latest
        - chmod 600 ~/.ssh/id_rsa
        - rsync -az --delete ./docker-compose.yml root@$SERVER_IP:science-innovate-admin/
        - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$SERVER_IP "cd science-innovate-admin/;docker-compose
          -f docker-compose.yml pull;docker-compose -f docker-compose.yml up -d;exit"
notifications:
  email:
    - 583403411@qq.com
  on_success: change
  on_failure: always
before_install:
  - openssl aes-256-cbc -K $encrypted_a7dfe7f624ec_key -iv $encrypted_a7dfe7f624ec_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d